# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  language: "en"
  nerdFontsVersion: "3"
git:
  # requires external tool git-delta (cargo install git-delta)
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
